import { Inter } from 'next/font/google';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-background text-foreground">
        {/* this can be removed, just a test */}
        <h1> Hello Team</h1>
        {/* this can be removed, just a test */}
        <button className="text-primary bg-foreground">Tailwind Test</button>
      </main>
    </>
  );
}
