import Head from 'next/head'
import dynamic from 'next/dynamic';
import styles from '@/styles/Home.module.css'


const MapWithNoSSR = dynamic(() => import('../lib/Components/Map'), {
  ssr: false,
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>  
      <MapWithNoSSR />
      </main>
    </>
  )
}
